### ISSUE TITLE
reshift

### ISSUE THREAD

**Issue by chandancode** [chandancode/resdhift#1]
resource "aws_s3_bucket" "apps_bucket" {
  bucket = "myredbucknew"
  acl = "private"
  tags {
      Name = "bucket-name"
  }
}

resource "aws_iam_role" "web_iam_role" {
  name = "web_iam_role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "redshift.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "web_iam_role_policy" {
  name = "web_iam_role_policy"
  role = "${aws_iam_role.web_iam_role.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": ["arn:aws:s3:::myredbucknew"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject"
      ],
      "Resource": ["arn:aws:s3:::myredbucknew/*"]
    }
  ]
}
EOF
}

resource "aws_redshift_cluster" "default" {
  cluster_identifier           = "myredhshift"
  database_name                = "myreddb"
  master_username              = "admin"
  master_password              = "xxxxxxxx"
  node_type                    = "dc1.large"
  cluster_type                 = "multi-node"
  vpc_security_group_ids       = ["sg-9ea95ef6"]
  cluster_subnet_group_name    = "default"
  encrypted                    = "false"
  number_of_nodes              = "2"
  iam_roles                    = ["${aws_iam_role.web_iam_role.name}"]
  skip_final_snapshot          = "true"
  tags {
    environment   = "PROD"
  }
}

output "Endpoint" {

  value = "${aws_redshift_cluster.default.endpoint}"

}

output "S3 url" {

  value = "${aws_s3_bucket.apps_bucket.arn}"
}

**Comment by imyashvinder** [comment]
It's because you are using (dot)name.
You must use (dot)arn attribute instead of name because you aren't attaching the name with the resource but the arn associated with that role.

Have a nice day
